language: java
sudo: false
install: true
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
      -Dsonar.host.url=https://sonarcloud.io
      -Dsonar.organization=parisjug
      -Dsonar.login=${SONARCLOUD_TOKEN}
      -Dsonar.branch.name=${TRAVIS_BRANCH}
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'